Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: '#80-character-limits'
  Enabled: false

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: '#consistent-string-literals'
  Enabled: false

Style/NumericLiterals:
  Description: >-
    Add underscores to large numeric literals to improve their
    readability.
  StyleGuide: '#underscores-in-numerics'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/DateTime:
  Description: 'Use Date or Time over DateTime.'
  StyleGuide: '#date--time'
  Enabled: false

Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Enabled: false

Style/Lambda:
  Description: 'Use the new lambda literal syntax for single-line blocks.'
  StyleGuide: '#lambda-multi-line'
  Enabled: false

Lint/UnusedBlockArgument:
  Description: 'Checks for unused block arguments.'
  StyleGuide: '#underscore-unused-vars'
  Enabled: false

Layout/EmptyLines:
  Description: "Don't use several empty lines in a row."
  StyleGuide: '#two-or-more-empty-lines'
  Enabled: false

Layout/AlignHash:
  Description: >-
    Align the elements of a hash literal if they span more than
    one line.
  Enabled: false

Bundler/OrderedGems:
  Description: >-
    Gems within groups in the Gemfile should be alphabetically sorted.
  Enabled: false
  Include:
    - '**/*.gemfile'
    - '**/Gemfile'
    - '**/gems.rb'

Style/GuardClause:
  Description: 'Check for conditionals that can be replaced with guard clauses'
  StyleGuide: '#no-nested-conditionals'
  Enabled: false

  Layout/EndOfLine:
    Description: 'Use Unix-style line endings.'
    StyleGuide: '#crlf'
    Enabled: false
